#!/bin/sh
xrandr \
    --output HDMI-0 --primary --mode 1920x1080 \
    --pos 1920x0 --rotate normal \
    --output DVI-D-0 --off \
    --output DP-0 --off \
    --output DP-1 --off --output DP-2 --off --output DP-3 --off \
    --output DP-4 --off --output DP-5 --off

xwallpaper --output HDMI-0 --center $WALLPAPER_DIR/moon-1440p.jpg

echo "HDMI-0" > $MON_CONF
