#!/bin/bash

[[ "$(setxkbmap -query | grep variant | awk '{print $NF}')" == "qwerty" ]] &&
    cat ~/.config/i3/{baseconfig,qwertykeys} >> ~/.config/i3/config ||
    cat ~/.config/i3/{baseconfig,wokmokkeys} >> ~/.config/i3/config

i3-msg reload
