#!/bin/bash

killall -q xcape

if [[ "$(setxkbmap -query | grep variant | awk '{print $NF}')" == "qwerty" ]]; then
    setxkbmap -layout gfkl -variant wokmok_lshift -model pc105 -option altwin:swap_lalt_lwin
    xcape -e '#66=Escape;#23=Tab' -t 200
else
    setxkbmap -layout gfkl -variant qwerty -model pc105 -option altwin:swap_lalt_lwin
fi

bash $HOME/.config/i3/reloadconfig
