#!/bin/bash

killall -q xcape

cat ~/.i3/baseconfig > ~/.i3/config
cat ~/.i3/workmakkeys >> ~/.i3/config

setxkbmap -layout gfkl -variant wokmok_lshift -model pc105 -option altwin:swap_lalt_lwin
xcape -e '#66=Escape;#23=Tab' -t 200

i3-msg reload
