#!/bin/bash

if [ "$(setxkbmap -query | grep variant | awk '{print $NF}')" = "qwerty" ]; then
    setxkbmap -layout gfkl -variant wokmok_lshift -model pc105 -option altwin:swap_lalt_lwin
else
    setxkbmap -layout gfkl -variant qwerty -model pc105 -option altwin:swap_lalt_lwin
fi
