#!/bin/bash

a=0

while getopts ":a" opt; do
    case $opt in
        a)
            a=1
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
        esac
    done

killall -q xcape
((a)) && cat ~/.i3/baseconfig > ~/.i3/config

if [[ "$(setxkbmap -query | grep variant | awk '{print $NF}')" == "qwerty" ]]; then
    ((a)) && cat ~/.i3/wokmokkeys >> ~/.i3/config
    setxkbmap -layout gfkl -variant wokmok_lshift -model pc105 -option altwin:swap_lalt_lwin
    xcape -e '#66=Escape;#23=Tab' -t 200
else
    ((a)) && cat ~/.i3/qwertykeys >> ~/.i3/config
    setxkbmap -layout gfkl -variant qwerty -model pc105 -option altwin:swap_lalt_lwin
fi

((a)) && i3-msg reload
