#! /bin/sh

killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
killall picom;
picom -b &
#killall bspswallow;
#pgrep bspswallow || bspswallow &
configureworkspaces "$1"
amixer sset 'Master' 80%

# CONFIG
bspc config border_width         1
bspc config window_gap           15
bspc config split_ratio          0.5
bspc config focused_border_color \#BF616A
bspc config normal_border_color  \#1c1f24
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# WINDOW RULES
bspc config external_rules_command "$HOME/dotfiles/config/bspwm/external-rules"

bspc rule -a Steam desktop=w
bspc rule -a Minecraf desktop=v
bspc rule -a discord desktop=j
bspc rule -a Code desktop=t
bspc rule -a Guitarix desktop=r
bspc rule -a Zathura state=tiled
bspc rule -a float state=floating rectangle=1600x900+0+0 center=true

steamlib=/home/malte/.local/share/Steam
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits
for game in $mygames; do
    bspc rule -a steam_app_$game desktop=v
done
