#!/bin/bash

options="switch layout
choose layout
pass
monitor
resets"

layouts="wokmok
us intl
danish"

resets="monitors
workspaces
rate
background
dimensions
polybar
sxhkd"

chosen="$(echo "$options" | dmenu -i -ae -c -fn 'pixelsize=20' -l 10)" || exit 1

case "$chosen" in
    "switch layout")
        if [[ "$(setxkbmap -query | grep layout | awk '{print $NF}')" == "gfkl" ]]
        then
            setlayout -u
        else
            setlayout -w
        fi
        startsxhkd;;

    "choose layout")
        chosen="$(echo "$layouts" | dmenu -i -ae -c -fn 'pixelsize=20' -l 4)" || exit 1
        case "$chosen" in
            "wokmok") setlayout -w;;
            "us intl") setlayout -u;;
            "danish") setlayout -d;;
        esac
        startsxhkd;;

    "pass")
        passmenu &;;

    "monitor")
        selectmon;;

    "resets")
        chosen="$(echo "$resets" | dmenu -i -ae -c -fn 'pixelsize=20' -l 7)" || exit 1
        case "$chosen" in
            "monitors") fixmonitors;;
            "workspaces") configureworkspaces;;
            "rate") xset r rate 200 25;;
            "background") setbg;;
            "dimensions") fixdimensions;;
            "polybar") startpolybar;;
            "sxhkd") startsxhkd;;
        esac;;
esac
