#!/bin/bash

options="switch layout
choose layout
pass
monitor
resets
bluetooth"

layouts="wokmok
us intl
danish"

resets="monitors
workspaces
background
polybar
rate
dimensions
sxhkd"

chosen="$(echo "$options" | dmenu -i -ae -c -fn 'pixelsize=20' -l 10)" || exit 1

case "$chosen" in
    "switch layout")
        if [[ "$(setxkbmap -query | grep layout | awk '{print $NF}')" == "gfkl" ]]
        then
            setlayout -u
        else
            setlayout -w
        fi
        startsxhkd;;

    "choose layout")
        chosen="$(echo "$layouts" | dmenu -i -ae -c -fn 'pixelsize=20' -l 4)" || exit 1
        case "$chosen" in
            "wokmok") setlayout -w;;
            "us intl") setlayout -u;;
            "danish") setlayout -d;;
        esac
        startsxhkd;;

    "pass")
        passmenu &;;

    "monitor")
        selectmon;;

    "resets")
        chosen="$(echo "$resets" | dmenu -i -ae -c -fn 'pixelsize=20' -l 7)" || exit 1
        case "$chosen" in
            "monitors") reloadmonitors;;
            "workspaces") configureworkspaces;;
            "background") setbg;;
            "polybar") startpolybar;;
            "rate") xset r rate 200 25;;
            "dimensions") fixdimensions;;
            "sxhkd") startsxhkd;;
        esac;;
    "bluetooth")
        devices=$(cat $HOME/files/os/bluetooth/trusted_devices.txt)
        declare -A macmap
        while IFS= read -r line; do
            read mac name <<< "$line"
            opts+="$name\n"
            macmap["$name"]="$mac"
        done <<< "$devices"

        opts+="stop"
        chosen="$(echo -e "$opts" | dmenu -i -c -fn 'pixelsize=20' -l 4)" || exit 1
        case "$chosen" in
            "stop")
                bluetoothctl power off
                exit 0;;
        esac
        mac="${macmap["$chosen"]}"
        bluetoothctl power on
        bluetoothctl connect "$mac"
        umac="${mac//:/_}"
        sink="bluez_output.$umac.1"
        pactl set-default-sink "$sink"
        ;;
esac
