vim.cmd('set number relativenumber')
vim.cmd('set tabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set expandtab')
-- vim.cmd('set autoindent')
-- vim.cmd('set smartindent')
vim.cmd('set noshowmode')
vim.cmd('set colorcolumn=101')
vim.cmd('set splitbelow')
vim.cmd('set splitright')

vim.cmd('set termguicolors')
vim.cmd('colorscheme nightfly')
vim.cmd('hi Normal guibg=NONE ctermbg=NONE guifg=#f5e6d1')
vim.cmd('hi NormalNC guibg=NONE ctermbg=NONE guifg=#f5e6d1')
vim.cmd('hi NormalFloat guibg=NONE ctermbg=NONE guifg=#f5e6d1')
vim.cmd('hi LineNr guibg=NONE ctermbg=NONE')
vim.cmd('hi Folded guibg=NONE ctermbg=NONE')
vim.cmd('hi NonText guibg=NONE ctermbg=NONE')
vim.cmd('hi SpecialKey guibg=NONE ctermbg=NONE')
vim.cmd('hi VertSplit guibg=NONE ctermbg=NONE')
vim.cmd('hi SignColumn guibg=NONE ctermbg=NONE')
vim.cmd('hi EndOfBuffer guibg=NONE ctermbg=NONE')
vim.cmd('hi CursorLineNr guibg=NONE ctermbg=NONE')
