vim.cmd('set number relativenumber')
vim.cmd('set tabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set expandtab')
-- vim.cmd('set autoindent')
-- vim.cmd('set smartindent')
vim.cmd('set noshowmode')
vim.cmd('set colorcolumn=101')
vim.cmd('set splitbelow')
vim.cmd('set splitright')
