#! /bin/sh

[[ -f ~/.bashrc ]] && . ~/.bashrc
export PATH="$HOME/dotfiles/scripts:$PATH"

# Random stuff, check this some time
#export QT_QPA_PLATFORMTHEME="qt5ct"
#export EDITOR=/usr/bin/vim
#export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
#export BROWSER=/usr/bin/google-chrome-stable
. "$HOME/.cargo/env"

# opam configuration
test -r /home/malte/.opam/opam-init/init.sh && . /home/malte/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
