#! /bin/sh

/home/malte/dotfiles/local/monitorlayout.sh

xset r rate 200 25
xautolock -time 25 -locker 'i3lock -c 1c1f24' &
redshift -l 57.01:9.58 &

# KEYBOARD LAYOUT
setxkbmap -layout gfkl -variant wokmok_lshift \
    -model pc105 -option altwin:swap_lalt_lwin &
xcape -e '#66=Escape;#23=Tab' -t 180 &

gitwatch ~/repos/vimwiki &

exec bspwm
