#! /bin/sh

export PATH="$HOME/dotfiles/scripts:$HOME/dotfiles/scripts/wm:$HOME/dotfiles/scripts/dmenu:$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Defaults
export TERMI="alacritty"
export EDITOR='vi -e'
export VISUAL='nvim'
export BROWSER="/usr/bin/brave"

source $HOME/.local/share/malteos/localsetup

# Monitor setup
export WALLPAPER_DIR="$HOME/files/wallpapers"
export MON_CONF="$HOME/.local/share/malteos/monitorconf"
export MON_SCRIPT="$HOME/.local/share/malteos/monitorscript"

. "$HOME/.cargo/env"

# opam configuration
test -r /home/malte/.opam/opam-init/init.sh && . /home/malte/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
