#! /bin/sh

export PATH="$HOME/malteos/scripts:$HOME/malteos/scripts/wm:$HOME/malteos/scripts/dmenu:$HOME/malteos/scripts/standalone:$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Defaults
export TERMI="alacritty"
export EDITOR='vi -e'
export VISUAL='nvim'
export BROWSER="/usr/bin/brave"

# Monitor setup
export WALLPAPER_DIR="$HOME/files/os/wallpapers"
export MON_CONF="$HOME/.local/share/malteos/monitorconf"
export MON_SCRIPT="$HOME/.local/share/malteos/monitorscript"

source $HOME/.local/share/malteos/localsetup

. "$HOME/.cargo/env"
