set number relativenumber
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set incsearch
set nocompatible
set noshowmode
set colorcolumn=81
set spelllang=en_us
set spell
filetype plugin indent on
syntax on
set so=12

call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
Plug 'yggdroot/indentline'
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'vimwiki/vimwiki'
Plug 'romgrk/doom-one.vim'
Plug 'morhetz/gruvbox'
Plug 'tmsvg/pear-tree'
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh'
    \ }
Plug 'lervag/vimtex'
Plug 'junegunn/fzf'
Plug 'eddyekofo94/gruvbox-flat.nvim'

call plug#end()

autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
iabbrev </ </<C-X><C-O>

let g:vimwiki_global_ext = 0
let g:vimwiki_list = [{
        \ 'path': '~/files/vimwiki/text/',
        \ 'path_html': '~/files/vimwiki/vimwiki_html/', 
        "\ 'syntax': 'markdown',
        "\ 'ext': '.md',
        \ 'template_path': '~/files/vimwiki/templates/',
        \ 'template_default': 'default'}]
let g:indentLine_concealcursor=""
let g:indentLine_conceallevel=2
autocmd FileType wiki nnoremap <Esc> :VimwikiGoBackLink<CR>

let g:LanguageClient_serverCommands = {
        \ 'rust': ['rust-analyzer'],
        \ }

let g:vimtex_view_method = 'zathura'
let g:vimtex_syntax_conceal_disable = 1

nnoremap <SPACE> <Nop>
let mapleader = " "
let maplocalleader = ","
nnoremap Y y$
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
let g:lightline = {'colorscheme': 'one'}

"COLORS
"let g:gruvbox_invert_selection=0
"let g:gruvbox_contrast_dark='hard'
"set bg=dark
set termguicolors
"colorscheme gruvbox
colorscheme gruvbox-flat
let g:gruvbox_flat_style = "dark"
"colorscheme doom-one
hi Normal guibg=NONE ctermbg=NONE guifg=#f5e6d1
hi LineNr guibg=NONE ctermbg=NONE
hi Folded guibg=NONE ctermbg=NONE
hi NonText guibg=NONE ctermbg=NONE
hi SpecialKey guibg=NONE ctermbg=NONE
hi VertSplit guibg=NONE ctermbg=NONE
hi SignColumn guibg=NONE ctermbg=NONE
hi EndOfBuffer guibg=NONE ctermbg=NONE
hi CursorLineNr guibg=NONE ctermbg=NONE

"COMMENTING
nmap <C-_> <leader>c<Space>
vmap <C-_> <leader>c<Space>

"PARENTHESIS COMPLETION
let g:pear_tree_smart_openers = 1
let g:pear_tree_smart_closers = 1
let g:pear_tree_smart_backspace = 1

"OPEN LINES
nnoremap <silent> <leader>o 
            \:<C-u>call append(line("."),   repeat([""], v:count1))<CR>
nnoremap <silent> <leader>O 
            \:<C-u>call append(line(".")-1, repeat([""], v:count1))<CR>

"KEEP CENTER WHEN SEARCHING
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap J mzJ`z

"SYSTEM CLIPBOARD
nnoremap <leader>y <S-v>"+y
vnoremap <leader>y "+y
nnoremap <leader>p "+p
vnoremap <leader>p "_dP

"SELECT ALL
nnoremap <leader>a gg<S-v>G

"MOVE TEXT
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
inoremap <C-j> <esc>:m .+1<CR>==
inoremap <C-k> <esc>:m .-2<CR>==
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==

"UNDO POINTS
inoremap , ,<C-g>u
inoremap . .<C-g>u
inoremap ! !<C-g>u
inoremap ? ?<C-g>u

"LATEX
autocmd FileType tex inoremap ;fr \begin{frame}<Enter>\frametitle{}<Enter><Enter>(<>)<Enter><Enter>\end{frame}<Enter><Enter>(<>)<Esc>6kf}i

autocmd FileType tex inoremap ;mt \begin{matrix}  \end{matrix}<Esc>Bhi
autocmd FileType tex inoremap ;mp \begin{pmatrix}  \end{pmatrix}<Esc>Bhi
autocmd FileType tex inoremap ;mb \begin{bmatrix}  \end{bmatrix}<Esc>Bhi
autocmd FileType tex inoremap ;mB \begin{Bmatrix}  \end{Bmatrix}<Esc>Bhi
autocmd FileType tex inoremap ;mv \begin{vmatrix}  \end{vmatrix}<Esc>Bhi
autocmd FileType tex inoremap ;mV \begin{Vmatrix}  \end{Vmatrix}<Esc>Bhi

autocmd FileType tex inoremap ;ai \begin{align*}<Enter><Enter>\end{align*}<Enter>(<>)<Esc>2ki<Tab>
autocmd FileType tex inoremap ;an \begin{align}<Enter><Enter>\end{align}<Enter>(<>)<Esc>2ki<Tab>

autocmd FileType tex inoremap ;se \section{}<Enter>(<>)<Esc>k$i
autocmd FileType tex inoremap ;sn \section*{}<Enter>(<>)<Esc>k$i
autocmd FileType tex inoremap ;1se \subsection{}<Enter>(<>)<Esc>k$i
autocmd FileType tex inoremap ;1sn \subsection*{}<Enter>(<>)<Esc>k$i
autocmd FileType tex inoremap ;2se \subsubsection{}<Enter>(<>)<Esc>k$i
autocmd FileType tex inoremap ;2sn \subsubsection*{}<Enter>(<>)<Esc>k$i
autocmd FileType tex inoremap ;3se \subsubsubsection{}<Enter>(<>)<Esc>k$i
autocmd FileType tex inoremap ;3sn \subsubsubsection*{}<Enter>(<>)<Esc>k$i

autocmd FileType tex inoremap ;fra \frac{}{(<>)}(<>)<Esc>10hi

autocmd FileType tex inoremap <leader><Space> <Esc>/(<>)<CR>:noh<CR>cf)
autocmd FileType tex nnoremap <leader><Space> <Esc>/(<>)<CR>:noh<CR>cf)

"DISABLE ARROW KEYS
inoremap <Up> <Nop>
inoremap <Down> <Nop>
inoremap <Left> <Nop>
inoremap <Right> <Nop>

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>
