#!/bin/bash

layouts="wokmok
us
danish"
chosen="$(echo "$layouts" | dmenu -i -c -fn 'pixelsize=20' -l 4 -p "Layout:")" || exit 1

killall -q xcape
killall sxhkd

case "$chosen" in
    "wokmok") 
        setxkbmap -layout gfkl -model pc105 -option altwin:swap_lalt_lwin
        xcape -e '#66=Escape;#23=Tab' -t 180;;
    "us")
        setxkbmap -layout us -variant altgr-intl -model pc105 -option altwin:swap_lalt_lwin;;
    "danish")
        setxkbmap -layout dk -model pc105 -option altwin:swap_lalt_lwin;;
esac

[[ "$(setxkbmap -query | grep variant | awk '{print $NF}')" == "wokmok_lshift" ]] &&
    cat ~/dotfiles/config/sxhkd/{base,wokmok} > ~/.config/sxhkd/sxhkdrc ||
    cat ~/dotfiles/config/sxhkd/{base,qwerty} > ~/.config/sxhkd/sxhkdrc

pgrep -x sxhkd > /dev/null || sxhkd &
