#!/bin/bash

. $HOME/.dmenurc

layouts="wokmok
qwerty
us
danish"
chosen="$(echo "$layouts" | dmenu $DMENU_OPTIONS -i -l 10 -y 200 -x 400 -w 1120 -p "Choose Layout:")" || exit 1

killall -q xcape
killall sxhkd

case "$chosen" in
    "wokmok") 
        setxkbmap -layout gfkl -variant wokmok_lshift -model pc105 -option altwin:swap_lalt_lwin
        xcape -e '#66=Escape;#23=Tab' -t 180;;
    "qwerty")
        setxkbmap -layout gfkl -variant qwerty -model pc105 -option altwin:swap_lalt_lwin;;
    "us")
        setxkbmap -layout us -variant altgr-intl -model pc105 -option altwin:swap_lalt_lwin;;
    "danish")
        setxkbmap -layout dk -model pc105 -option altwin:swap_lalt_lwin;;
esac

[[ "$(setxkbmap -query | grep variant | awk '{print $NF}')" == "wokmok_lshift" ]] &&
    cat ~/dotfiles/config/sxhkd/{base,wokmok} > ~/.config/sxhkd/sxhkdrc ||
    cat ~/dotfiles/config/sxhkd/{base,qwerty} > ~/.config/sxhkd/sxhkdrc

pgrep -x sxhkd > /dev/null || sxhkd &
