#!/bin/bash

dlvideo=false
OPTIND=1

while getopts ":v" opt; do
    case $opt in
        v) dlvideo=true;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

shift $((OPTIND-1))

if [[ $# -ne 2 && $# -ne 3 ]] ; then
    exit 0
fi

if [ "$dlvideo" = true ]; then
    yt-dlp -o $HOME/largefiles/saved/videos/$1.webm "$2"
fi

yt-dlp -x --audio-format wav -o $HOME/largefiles/saved/music/$1.wav "$2" &&
ffmpeg -i $HOME/largefiles/saved/music/$1.wav -acodec mp3 $HOME/largefiles/saved/spotify/$1.mp3
