#!/bin/bash

HOME_DIR=""
HOME_PATH=""
SEARCH_DIRS=""
EXCLUDED_DIRS=""

while getopts ":hE" opt; do
    case $opt in
        h) 
            HOME_DIR="--base-directory $HOME"
            HOME_PATH="$HOME/"
            SEARCH_DIRS="dotfiles/ repos/ files/"
            ;;
        E)
            EXCLUDED_DIRS="-E files/minecraft/"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

line=$(fd . $SEARCH_DIRS $HOME_DIR -H --no-ignore-vcs -t f $EXCLUDED_DIRS |
    dmenu -i -c -fn 'pixelsize=15' -l 15)
[ -z "$line" ] && exit
fileext=$(echo $line | cut -d. -f2)
case $fileext in
    link)
        $BROWSER $(cat $HOME_PATH$line)
        ;;
    pdf)
        zathura $HOME_PATH$line
        ;;
    wiki)
        alacritty -e nvim $HOME_PATH$line
        ;;
    *)
        filetype=$(file --mime-type $HOME_PATH$line | cut -d\  -f2)
        case $filetype in
            text*)
                alacritty -e nvim $HOME_PATH$line
                ;;
            image*)
                sxiv $HOME_PATH$line
                ;;
            audio*|video*)
                vlc $HOME_PATH$line
                ;;
            *json*)
                alacritty -e nvim $HOME_PATH$line
                ;;
            *)
                xdg-open 2>&- $HOME_PATH$line;
                ;;
        esac
        ;;
esac
