#!/bin/bash

chosen=""

while getopts ":wud" opt; do
    case $opt in
        w) chosen="wokmok";;
        u) chosen="us";;
        d) chosen="danish";;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

if [[ $# -eq 0 ]] ; then
    exit 0
fi

killall -q xcape
killall sxhkd

case "$chosen" in
    "wokmok") 
        setxkbmap -layout gfkl -model pc105
        xcape -e '#66=Escape;#23=Tab;#36=Return;#64=F12' -t 180;;
    "us")
        setxkbmap -layout us -variant altgr-intl -model pc105 -option altwin:swap_lalt_lwin
        xcape -e '#64=F12' -t 180;;
    "danish")
        setxkbmap -layout dk -model pc105 -option altwin:swap_lalt_lwin
        xcape -e '#64=F12' -t 180;;
esac
[[ "$(setxkbmap -query | grep layout | awk '{print $NF}')" == "gfkl" ]] &&
    cat ~/dotfiles/config/sxhkd/{base,wokmok} > ~/.config/sxhkd/sxhkdrc ||
    cat ~/dotfiles/config/sxhkd/{base,qwerty} > ~/.config/sxhkd/sxhkdrc

pgrep -x sxhkd > /dev/null || sxhkd &
