#!/bin/bash

options="switch layout
choose layout
pass
network
monitor
fixmonitors"

layouts="wokmok
us intl
danish"

chosen="$(echo "$options" | dmenu -i -ae -c -fn 'pixelsize=20' -l 10)" || exit 1

case "$chosen" in
    "switch layout")
        if [[ "$(setxkbmap -query | grep layout | awk '{print $NF}')" == "gfkl" ]]
        then
            layout -u
        else
            layout -w
        fi;;

    "choose layout")
        chosen="$(echo "$layouts" | dmenu -i -ae -c -fn 'pixelsize=20' -l 4)" || exit 1
        case "$chosen" in
            "wokmok") layout -w;;
            "us intl") layout -u;;
            "danish") layout -d;;
        esac;;

    "pass")
        #alacritty --class smallfloat,smallfloat -e passmenu;;
        passmenu &;;

    "network")
        networkmanager_dmenu;;

    "monitor")
        selectmon;;

    "fixmonitors")
        fixmonitors;;

esac
