#!/bin/bash

HOME_DIR=""
HOME_PATH=""
EXCLUDED_DIRS=""

while getopts ":hE" opt; do
    case $opt in
        h) 
            HOME_DIR="--base-directory $HOME"
            HOME_PATH="$HOME/"
            ;;
        E)
            EXCLUDED_DIRS="-E go/bin/ -E go/pkg/ -E .local/lib/ -E .themes/ -E .cache/ -E .cargo/ -E .wine/drive_c/ -E .config/google-chrome/ -E .config/discord/ -E .vscode-oss/ -E .vscode/ -E .config/Code/"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

fd $HOME_DIR -t f -H $EXCLUDED_DIRS | fzf -m --preview="head -30 $HOME_PATH{}" | while read line ; do
    fileext=$(echo $line | cut -d. -f2)
    echo $fileext
    case $fileext in
        link)
            echo $(cat $HOME_PATH$line) | xargs -ro -d "\n" $BROWSER
            ;;
        pdf)
            echo $HOME_PATH$line | xargs -ro -d "\n" zathura
            ;;
        wiki)
            echo $HOME_PATH$line | xargs -ro -d "\n" nvim
            ;;
        *)
            filetype=$(file --mime-type $HOME_PATH$line | cut -d\  -f2)
            case $filetype in
                text*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" nvim
                    ;;
                image*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" sxiv
                    ;;
                audio*|video*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" vlc
                    ;;
                *json*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" nvim
                    ;;
                *)
                    echo $HOME_PATH$line | xargs -ro -d "\n" xdg-open 2>&-
                    ;;
            esac
            ;;
    esac
done
