#!/bin/bash

HOME_DIR=""
HOME_PATH=""
SEARCH_DIRS=""
EXCLUDED_DIRS=""

while getopts ":hE" opt; do
    case $opt in
        h) 
            HOME_DIR="--base-directory $HOME"
            HOME_PATH="$HOME/"
            SEARCH_DIRS="dotfiles/ repos/ files/"
            ;;
        E)
            EXCLUDED_DIRS="-E files/minecraft/"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit
            ;;
    esac
done

fd . $SEARCH_DIRS $HOME_DIR -H --no-ignore-vcs -t f $EXCLUDED_DIRS | 
    fzf -m --preview="head -30 $HOME_PATH{}" | while read line ; do
    fileext=$(echo $line | cut -d. -f2)
    echo $line
    case $fileext in
        link)
            echo $(cat $HOME_PATH$line) | xargs -ro -d "\n" $BROWSER
            ;;
        pdf)
            echo $HOME_PATH$line | nohup xargs -ro -d "\n" zathura; exit
            ;;
        wiki)
            echo $HOME_PATH$line | xargs -ro -d "\n" nvim
            ;;
        *)
            filetype=$(file --mime-type $HOME_PATH$line | cut -d\  -f2)
            case $filetype in
                text*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" nvim
                    ;;
                image*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" sxiv
                    ;;
                audio*|video*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" vlc
                    ;;
                *json*)
                    echo $HOME_PATH$line | xargs -ro -d "\n" nvim
                    ;;
                *)
                    echo $HOME_PATH$line | xargs -ro -d "\n" xdg-open 2>&-;
                    ;;
            esac
            ;;
    esac
done
