#!/bin/bash

DIR="0"
while getopts ":d" opt; do
    case $opt in
        d)
            DIR="1";;
    esac
done

file () {
    alacritty --class float,float -e of "$@"
    cmd=`cat ~/.cache/ofcmd`
    $cmd &
}

dir () {
    alacritty --class float,float -e of "$@" -d
    path=`cat ~/.cache/ofcmd`
    [ -n "$path" ] && alacritty --working-directory "$path"
}

if [ "$DIR" -eq "0" ]; then
    file "$@"
else
    dir "$@"
fi
