#!/bin/bash

if [[ $# -eq 1 ]]; then
  _root_dir="$(git -C $1 rev-parse --show-toplevel 2>/dev/null)"
else
  _root_dir="$(git rev-parse --show-toplevel 2>/dev/null)"
fi

if [[ $? -gt 0 ]]; then
  pwd
else 
  echo $_root_dir
fi
