#!/bin/bash

killall -q xcape
killall sxhkd

if [[ "$(setxkbmap -query | grep variant | awk '{print $NF}')" == "wokmok_lshift" ]]
then
    setxkbmap -layout us -variant altgr-intl -model pc105 -option altwin:swap_lalt_lwin
    cat ~/dotfiles/config/sxhkd/{base,qwerty} > ~/.config/sxhkd/sxhkdrc
else
    setxkbmap -layout gfkl -variant wokmok_lshift -model pc105 -option altwin:swap_lalt_lwin
    xcape -e '#66=Escape;#23=Tab' -t 180
    cat ~/dotfiles/config/sxhkd/{base,wokmok} > ~/.config/sxhkd/sxhkdrc
fi

pgrep -x sxhkd > /dev/null || sxhkd &
